[[main]]
name = "Math"
pageRef = "math"
weight = 1

[[main]]
name = "Systems"
pageRef = "systems"
weight = 2

[[main]]
name = "Academics"
pageRef = "academics"
weight = 3

[[main]]
name = "Projects"
pageRef = "projects"
weight = 4

[[main]]
name = "Journal"
pageRef = "journal"
weight = 5
